<?php

namespace Acseo\Bundle\StartupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StartupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StartupRepository extends EntityRepository
{
}